name: "Trigger Bot"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Bot
        run: |
          gh workflow run -R sevenc-nanashi/vv-preview-demo-bot update_pages.yml
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
